In [2]:
# Creating Arrays
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]

# Converting into a numpy array
my_array1 = np.array(my_list)

# See the output
print(f"This is the numpy array: {my_array1}")

This is the numpy array: [1 2 3 4]


In [4]:
my_list2 = [11, 22, 33, 44]

# Combine my_list with my_list2
my_lists = [my_list, my_list2]

# Declare an actual np array for my_lists
my_arrays = np.array(my_lists)
print(my_lists) # [[1, 2, 3, 4], [11, 22, 33, 44]]

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [10]:

print(f" For the numpy array {my_arrays}")

# Useful Numpy Methods
print(f"The shape is {my_arrays.shape}") # (2, 4) : As in two elements with 4 subelements
print(f"The Data type is {my_arrays.dtype}") # int32 : A data type that is being used
print(f"The amount or dimensions are {my_arrays.ndim}") # 2 : There are two dimensions

 For the numpy array [[ 1  2  3  4]
 [11 22 33 44]]
The shape is (2, 4)
The Data type is int32
The amount or dimensions are 2


In [6]:
# Creating an array with custom np methods
print(np.zeros(5)) # Create a 1d array with all zeros and 5 elements

[0. 0. 0. 0. 0.]


In [11]:
my_zeros_Array = np.zeros(5)

In [12]:
print(f"The data type is: {my_zeros_Array.dtype}")

The data type is: float64


In [13]:
# Array Method for ones
print(np.ones([5, 5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# Method to create empty values
print(np.empty(5)) # creates an array with zeros

[0. 0. 0. 0. 0.]


In [16]:
"""
An Identity Matrix is filled with 1s across its diagonal,
has every other position as 0s
"""
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# Gives evenly placed values given start and end

print(np.arange(5)) # [0 1 2 3 4]
print(np.arange(start=10, stop=20, step=2, dtype=np.float32)) #[10. 12. 14. 16. 18.]


[0 1 2 3 4]
[10. 12. 14. 16. 18.]
