In [1]:
import numpy as np

In [6]:
arr = np.arange(start=0, stop=11)


In [7]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
# Trivial Index
print(f" The 8th element is:\t {arr[8]}")

 The 8th element is 8


In [10]:
# You can use list indexing
print(arr[1:5]) # [1 2 3 4]
print(arr[0:5]) # [0 1 2 3 4]

[1 2 3 4]
[0 1 2 3 4]


In [14]:
# By using indexing, you can also assign values
arr[0:5] = 100
print(f"When changed through indexing, it becomes {arr}")

arr = np.arange(start=0, stop=11)
print(f" Changed it back into: {arr}")

When changed through indexing, it becomes [100 100 100 100 100   5   6   7   8   9  10]
 Changed it back into: [ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
# Slicing arrays
slice_of_arr = arr[0:6] # also inherits the dtype

print(slice_of_arr)

[0 1 2 3 4 5]


In [17]:
# Apply this to all elements
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99 99 99]


In [18]:
# Np array slices affect the thing itself
print(arr)

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
# For no interference I have to do .copy()

arr_copy = arr.copy()

In [21]:
# Making a 2d Array

arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(f"The 2d array becomes {arr_2d}")

The 2d array becomes [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [24]:
# Indexes
print(arr_2d[1])

[20 25 30]


In [25]:
# Getting columns
print(arr_2d[1][0])

20


In [27]:
# Creating a sub array within an array
print(arr_2d[:2, 1:]) # Everything but the last row and first column


[[10 15]
 [25 30]]


In [29]:
# Fancy Indexing
arr2d = np.zeros((10, 10))
print(arr2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
arr_length = arr2d.shape[1]
arr_length

10

In [33]:
for i in range(arr_length):
    arr2d[i] = i
print(arr2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [37]:
# Getting the subarray again!!
print(arr2d[[2, 4, 6, 8]])

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]
