In [1]:
import numpy as np

In [ ]:
from __future__ import division # allows operations to care about accuracy

In [13]:
arr1 = np.array([[1, 2, 3, 4],[8, 9, 10, 11]])
print(f"The array or rep of arr1 is {arr1}")

# Every single index within the respective
# Arrays gets multipled with the one at the
# same index
print(f"The multiped or squared array is {arr1 * arr1}")

The array or rep of arr1 is [[ 1  2  3  4]
 [ 8  9 10 11]]
[[  1   4   9  16]
 [ 64  81 100 121]]


In [14]:
print(arr1-arr1) # all zeros since they are all scalars

[[0 0 0 0]
 [0 0 0 0]]


In [16]:
# Getting a reciprocal for a function
print( 1 / arr1)

# Multiplying from exponet
print( arr1 ** 3)

[[1.         0.5        0.33333333 0.25      ]
 [0.125      0.11111111 0.1        0.09090909]]
[[   1    8   27   64]
 [ 512  729 1000 1331]]
