In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
# e ot the power of
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10) # A random normal distribution

A

array([ 0.77589147,  0.66304582,  0.58742012,  0.24493758, -1.00949362,
        0.01134247, -0.80545737, -1.17978533,  0.06881247,  0.4674137 ])

In [8]:
B = np.random.randn(10)

B

array([ 0.05432159,  0.89508427, -0.4748894 ,  1.14775963,  0.24252795,
       -0.97164206, -1.69367049,  0.20797784,  0.71443408, -1.25429308])

In [14]:
# --- Binary Functions ---
# There are more operations on scipy as well
# adding arrays
print(np.add(A, B), end="\n\n")

# finding the max or min
print(np.maximum(A, B), end="\n\n")
print(np.minimum(A, B), end="\n\n")


[ 0.83021306  1.55813009  0.11253072  1.39269721 -0.76696568 -0.96029959
 -2.49912786 -0.97180749  0.78324655 -0.78687938]

[ 0.77589147  0.89508427  0.58742012  1.14775963  0.24252795  0.01134247
 -0.80545737  0.20797784  0.71443408  0.4674137 ]

[ 0.05432159  0.66304582 -0.4748894   0.24493758 -1.00949362 -0.97164206
 -1.69367049 -1.17978533  0.06881247 -1.25429308]

