In [51]:
import numpy as np  

In [52]:
arr = np.arange(5)

In [53]:
arr

array([0, 1, 2, 3, 4])

In [54]:
np.save('myarray', arr)

In [55]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [56]:
arr1 = np.load('myarray.npy')

In [57]:
arr2 = arr

In [58]:
arr2 

array([0, 1, 2, 3, 4])

In [59]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [60]:
archive_array = np.load('ziparray.npz')

In [61]:
# While these are the same you can make them
# different

print(archive_array['x'])
print(archive_array['y'])

[0 1 2 3 4]
[0 1 2 3 4]


In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# delimiter is what seperates each value for rep
# it also has to be a single unicode character
np.savetxt('mytextarray.txt', arr, delimiter=',')

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr = np.loadtxt('mytextarray.txt', delimiter=',')